# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(626, 669)
        MainWindow.setMinimumSize(QtCore.QSize(626, 669))
        MainWindow.setMaximumSize(QtCore.QSize(626, 669))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(9, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_for_url = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_for_url.sizePolicy().hasHeightForWidth())
        self.label_for_url.setSizePolicy(sizePolicy)
        self.label_for_url.setObjectName("label_for_url")
        self.gridLayout.addWidget(self.label_for_url, 0, 0, 1, 2)
        self.controlLayout = QtWidgets.QGridLayout()
        self.controlLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.controlLayout.setContentsMargins(-1, 0, -1, -1)
        self.controlLayout.setObjectName("controlLayout")
        self.label_for_rus_name = QtWidgets.QLabel(self.centralwidget)
        self.label_for_rus_name.setObjectName("label_for_rus_name")
        self.controlLayout.addWidget(self.label_for_rus_name, 2, 0, 1, 1)
        self.label_for_eng_name = QtWidgets.QLabel(self.centralwidget)
        self.label_for_eng_name.setObjectName("label_for_eng_name")
        self.controlLayout.addWidget(self.label_for_eng_name, 0, 0, 1, 1)
        self.label_for_translated_name = QtWidgets.QLabel(self.centralwidget)
        self.label_for_translated_name.setObjectName("label_for_translated_name")
        self.controlLayout.addWidget(self.label_for_translated_name, 0, 1, 1, 1)
        self.card_name_rus = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.card_name_rus.setFont(font)
        self.card_name_rus.setObjectName("card_name_rus")
        self.controlLayout.addWidget(self.card_name_rus, 3, 0, 1, 1)
        self.card_name_eng = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.card_name_eng.setFont(font)
        self.card_name_eng.setObjectName("card_name_eng")
        self.controlLayout.addWidget(self.card_name_eng, 1, 0, 1, 1)
        self.save_changes = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.save_changes.setFont(font)
        self.save_changes.setStyleSheet("padding: 10px;")
        self.save_changes.setObjectName("save_changes")
        self.controlLayout.addWidget(self.save_changes, 4, 0, 1, 2)
        self.label_for_pnp_name = QtWidgets.QLabel(self.centralwidget)
        self.label_for_pnp_name.setObjectName("label_for_pnp_name")
        self.controlLayout.addWidget(self.label_for_pnp_name, 2, 1, 1, 1)
        self.card_name_translated = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.card_name_translated.setFont(font)
        self.card_name_translated.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.card_name_translated.setReadOnly(True)
        self.card_name_translated.setObjectName("card_name_translated")
        self.controlLayout.addWidget(self.card_name_translated, 1, 1, 1, 1)
        self.card_name_pnp = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.card_name_pnp.setFont(font)
        self.card_name_pnp.setObjectName("card_name_pnp")
        self.controlLayout.addWidget(self.card_name_pnp, 3, 1, 1, 1)
        self.gridLayout.addLayout(self.controlLayout, 6, 0, 1, 2)
        self.inputUrlLayout = QtWidgets.QHBoxLayout()
        self.inputUrlLayout.setObjectName("inputUrlLayout")
        self.deck_url = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deck_url.sizePolicy().hasHeightForWidth())
        self.deck_url.setSizePolicy(sizePolicy)
        self.deck_url.setObjectName("deck_url")
        self.inputUrlLayout.addWidget(self.deck_url)
        self.load_deck_btn = QtWidgets.QPushButton(self.centralwidget)
        self.load_deck_btn.setStyleSheet("padding: 3px 10px;")
        self.load_deck_btn.setObjectName("load_deck_btn")
        self.inputUrlLayout.addWidget(self.load_deck_btn)
        self.gridLayout.addLayout(self.inputUrlLayout, 4, 0, 1, 2)
        self.deckInfoLayout = QtWidgets.QHBoxLayout()
        self.deckInfoLayout.setObjectName("deckInfoLayout")
        self.deck_viewer = QtWidgets.QTreeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deck_viewer.sizePolicy().hasHeightForWidth())
        self.deck_viewer.setSizePolicy(sizePolicy)
        self.deck_viewer.setMinimumSize(QtCore.QSize(300, 420))
        self.deck_viewer.setMaximumSize(QtCore.QSize(300, 16777215))
        self.deck_viewer.setColumnCount(1)
        self.deck_viewer.setObjectName("deck_viewer")
        self.deck_viewer.headerItem().setText(0, "1")
        self.deckInfoLayout.addWidget(self.deck_viewer)
        self.card_face = QtWidgets.QLabel(self.centralwidget)
        self.card_face.setMinimumSize(QtCore.QSize(300, 426))
        self.card_face.setMaximumSize(QtCore.QSize(300, 426))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.card_face.setFont(font)
        self.card_face.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.card_face.setFrameShadow(QtWidgets.QFrame.Plain)
        self.card_face.setPixmap(QtGui.QPixmap(":/img/player-card-back.png"))
        self.card_face.setScaledContents(True)
        self.card_face.setObjectName("card_face")
        self.deckInfoLayout.addWidget(self.card_face)
        self.gridLayout.addLayout(self.deckInfoLayout, 5, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Arkham Horror Decker by Tre"))
        self.label_for_url.setText(_translate("MainWindow", "<html><head/><body><p>Введите адрес колоды с сайта <a href=\"https://arkhamdb.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">arkhamdb.com</span></a></p></body></html>"))
        self.label_for_rus_name.setText(_translate("MainWindow", "Название на русском"))
        self.label_for_eng_name.setText(_translate("MainWindow", "Название на английском"))
        self.label_for_translated_name.setText(_translate("MainWindow", "<html><head/><body><p>Перевод от <a href=\"https://translate.yandex.ru/\">Яндекс.Переводчик</a></p></body></html>"))
        self.save_changes.setText(_translate("MainWindow", "Сохранить изменения"))
        self.label_for_pnp_name.setText(_translate("MainWindow", "Текст в любительском переводе (PnP)"))
        self.load_deck_btn.setText(_translate("MainWindow", "Загрузить колоду"))

import View.res_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

